#!/bin/bash

if [ $1 == "build" ]; then
  docker-compose -f docker-compose.yml build
elif [ $1 == "up" ]; then
  docker-compose -f docker-compose.yml up -d
elif [ $1 == "logs" ]; then
  docker-compose -f docker-compose.yml logs -f
elif [ $1 == "migrate" ]; then
  docker-compose -f docker-compose.yml exec backend python manage.py migrate
elif [ $1 == "makemigrations" ]; then
  docker-compose -f docker-compose.yml exec backend python manage.py makemigrations
elif [ $1 == "merge" ]; then
  docker-compose -f docker-compose.yml exec backend python manage.py makemigrations --merge
elif [ $1 == "test" ]; then
  docker-compose -f docker-compose.yml exec backend python manage.py test
elif [ $1 == "seed" ]; then
  docker-compose -f docker-compose.yml exec backend python manage.py seeder
elif [ $1 == "makemessages" ]; then
  docker-compose -f docker-compose.yml exec backend python manage.py makemessages
elif [ $1 == "compilemessages" ]; then
  docker-compose -f docker-compose.yml exec backend python manage.py compilemessages
elif [ $1 == "collectstatic" ]; then
  docker-compose -f docker-compose.yml exec backend python manage.py collectstatic
elif [ $1 == "createsuperuser" ]; then
  docker-compose -f docker-compose.yml exec backend python manage.py createsuperuser
fi
